# Copyright (C) 2024 EmbeddedSolutions.pl

FROM docker.io/alpine:3.19

RUN apk add --no-cache \
  clang17-extra-tools \
  bash \
  black \
  curl \
  fd \
  git \
  py3-flake8 \
  py3-pip \
  ripgrep \
  shellcheck

RUN pip install --break-system-packages doc8

RUN curl -L \
  https://github.com/crate-ci/typos/releases/download/v1.19.0/typos-v1.19.0-x86_64-unknown-linux-musl.tar.gz | \
  tar -C /usr/local/bin -zxf - ./typos
